### ISSUE TITLE
modifikasi ommu zone

### ISSUE THREAD

**Issue by oMMuCo** [oMMu/Ommu-Core#4]
ommu zone disesuaikan dengan konsep http://mfdonline.bps.go.id

**Comment by oMMuCo** [comment]
country, province, city and district all fixed 

https://github.com/oMMu/Ommu-Core/commit/4385b7e794cfeb880a82848a3755b58ada146683
https://github.com/oMMu/Ommu-Core/commit/7eddda3a99c4191835cc99d483e1dcd8571f11c9
https://github.com/oMMu/Ommu-Core/commit/6ae0238604042248120ce4e2d466abb2769eb630
https://github.com/oMMu/Ommu-Core/commit/b30d8d9c502a7b07d6bf26086661996d752fe4e4

**Comment by oMMuCo** [comment]
village kalau bisa ditambahkan :-)

**Comment by PutraSudaryanto** [comment]
village fixed https://github.com/oMMu/Ommu-Core/commit/af17696de87140bead7fe2f2541993015d409b47
